/* ============================================
   QuizForge Mock Data — Realistic Demo Content
   ============================================ */

import type {
  User, Assessment, Question, QuestionBank, DashboardStats,
  Activity, AnalyticsData, Attempt, Certificate, Notification,
} from '@/types';

export const currentUser: User = {
  id: 'u1',
  email: 'sarah.chen@quizforge.io',
  name: 'Sarah Chen',
  avatar: undefined,
  role: 'admin',
  organization_id: 'org1',
  created_at: '2024-01-15T10:00:00Z',
};

export const mockQuestionBanks: QuestionBank[] = [
  {
    id: 'qb1',
    name: 'JavaScript Fundamentals',
    description: 'Core JavaScript concepts including variables, functions, closures, and async programming',
    question_count: 45,
    tags: ['javascript', 'programming', 'web'],
    created_by: 'u1',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-07-15T14:30:00Z',
  },
  {
    id: 'qb2',
    name: 'Data Structures & Algorithms',
    description: 'Arrays, linked lists, trees, graphs, sorting, and searching algorithms',
    question_count: 72,
    tags: ['dsa', 'algorithms', 'computer-science'],
    created_by: 'u1',
    created_at: '2024-05-20T08:00:00Z',
    updated_at: '2024-07-20T09:15:00Z',
  },
  {
    id: 'qb3',
    name: 'React & Modern Frontend',
    description: 'React hooks, state management, performance optimization, and testing',
    question_count: 38,
    tags: ['react', 'frontend', 'web'],
    created_by: 'u1',
    created_at: '2024-06-10T11:00:00Z',
    updated_at: '2024-07-18T16:45:00Z',
  },
  {
    id: 'qb4',
    name: 'Python for Data Science',
    description: 'NumPy, Pandas, Matplotlib, and machine learning fundamentals',
    question_count: 56,
    tags: ['python', 'data-science', 'ml'],
    created_by: 'u1',
    created_at: '2024-04-15T09:00:00Z',
    updated_at: '2024-07-22T11:30:00Z',
  },
  {
    id: 'qb5',
    name: 'System Design',
    description: 'Scalability, load balancing, caching, databases, and microservices',
    question_count: 30,
    tags: ['system-design', 'architecture', 'backend'],
    created_by: 'u1',
    created_at: '2024-07-01T10:00:00Z',
    updated_at: '2024-07-25T13:00:00Z',
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    bank_id: 'qb1',
    type: 'single_choice',
    title: 'What is a closure in JavaScript?',
    body: 'Which of the following best describes a closure in JavaScript?',
    options: [
      { id: 'o1', text: 'A function that has access to variables in its outer (enclosing) scope', is_correct: true, order: 0 },
      { id: 'o2', text: 'A function that is called immediately after it is defined', is_correct: false, order: 1 },
      { id: 'o3', text: 'A method to close a browser window', is_correct: false, order: 2 },
      { id: 'o4', text: 'A way to end a loop prematurely', is_correct: false, order: 3 },
    ],
    explanation: 'A closure is the combination of a function bundled together with references to its surrounding state (the lexical environment). This gives you access to an outer function\'s scope from an inner function.',
    hint: 'Think about scope and variable access.',
    points: 10,
    difficulty: 'medium',
    tags: ['closures', 'scope', 'functions'],
    category: 'Core Concepts',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'q2',
    bank_id: 'qb1',
    type: 'multiple_choice',
    title: 'Which are primitive data types in JavaScript?',
    body: 'Select all the primitive data types in JavaScript.',
    options: [
      { id: 'o5', text: 'string', is_correct: true, order: 0 },
      { id: 'o6', text: 'number', is_correct: true, order: 1 },
      { id: 'o7', text: 'object', is_correct: false, order: 2 },
      { id: 'o8', text: 'boolean', is_correct: true, order: 3 },
      { id: 'o9', text: 'symbol', is_correct: true, order: 4 },
      { id: 'o10', text: 'array', is_correct: false, order: 5 },
    ],
    explanation: 'JavaScript has 7 primitive types: string, number, bigint, boolean, undefined, symbol, and null. Objects and arrays are not primitives.',
    points: 15,
    difficulty: 'easy',
    tags: ['data-types', 'primitives'],
    category: 'Core Concepts',
    created_at: '2024-06-02T10:00:00Z',
    updated_at: '2024-06-02T10:00:00Z',
  },
  {
    id: 'q3',
    bank_id: 'qb1',
    type: 'true_false',
    title: 'JavaScript is a statically typed language',
    body: 'True or False: JavaScript is a statically typed language.',
    options: [
      { id: 'o11', text: 'True', is_correct: false, order: 0 },
      { id: 'o12', text: 'False', is_correct: true, order: 1 },
    ],
    explanation: 'JavaScript is a dynamically typed language. Variable types are determined at runtime, not at compile time. TypeScript adds static typing on top of JavaScript.',
    points: 5,
    difficulty: 'easy',
    tags: ['type-system'],
    category: 'Core Concepts',
    created_at: '2024-06-03T10:00:00Z',
    updated_at: '2024-06-03T10:00:00Z',
  },
  {
    id: 'q4',
    bank_id: 'qb1',
    type: 'fill_blank',
    title: 'Array method to transform elements',
    body: 'The array method _______ creates a new array by calling a function on every element in the original array.',
    options: [],
    correct_answer: 'map',
    explanation: 'The map() method creates a new array populated with the results of calling a provided function on every element in the calling array.',
    hint: 'Think about functional programming and transformation.',
    points: 10,
    difficulty: 'easy',
    tags: ['arrays', 'methods'],
    category: 'Arrays',
    created_at: '2024-06-04T10:00:00Z',
    updated_at: '2024-06-04T10:00:00Z',
  },
  {
    id: 'q5',
    bank_id: 'qb1',
    type: 'single_choice',
    title: 'Event Loop in JavaScript',
    body: 'What is the output of the following code?\n\nconsole.log("1");\nsetTimeout(() => console.log("2"), 0);\nPromise.resolve().then(() => console.log("3"));\nconsole.log("4");',
    options: [
      { id: 'o13', text: '1, 2, 3, 4', is_correct: false, order: 0 },
      { id: 'o14', text: '1, 4, 3, 2', is_correct: true, order: 1 },
      { id: 'o15', text: '1, 4, 2, 3', is_correct: false, order: 2 },
      { id: 'o16', text: '1, 3, 2, 4', is_correct: false, order: 3 },
    ],
    explanation: 'Synchronous code runs first (1, 4), then microtasks like Promises (3), then macrotasks like setTimeout (2).',
    points: 20,
    difficulty: 'hard',
    tags: ['event-loop', 'async', 'promises'],
    category: 'Async Programming',
    created_at: '2024-06-05T10:00:00Z',
    updated_at: '2024-06-05T10:00:00Z',
  },
  {
    id: 'q6',
    bank_id: 'qb1',
    type: 'essay',
    title: 'Explain Prototypal Inheritance',
    body: 'Explain how prototypal inheritance works in JavaScript. Include examples of the prototype chain and how objects inherit properties and methods.',
    options: [],
    points: 25,
    difficulty: 'hard',
    tags: ['prototypes', 'inheritance', 'oop'],
    category: 'Object-Oriented',
    created_at: '2024-06-06T10:00:00Z',
    updated_at: '2024-06-06T10:00:00Z',
  },
  {
    id: 'q7',
    bank_id: 'qb2',
    type: 'single_choice',
    title: 'Time complexity of binary search',
    body: 'What is the time complexity of binary search on a sorted array?',
    options: [
      { id: 'o17', text: 'O(n)', is_correct: false, order: 0 },
      { id: 'o18', text: 'O(log n)', is_correct: true, order: 1 },
      { id: 'o19', text: 'O(n log n)', is_correct: false, order: 2 },
      { id: 'o20', text: 'O(1)', is_correct: false, order: 3 },
    ],
    explanation: 'Binary search divides the search space in half with each comparison, resulting in O(log n) time complexity.',
    points: 10,
    difficulty: 'easy',
    tags: ['binary-search', 'time-complexity'],
    category: 'Searching',
    created_at: '2024-06-10T10:00:00Z',
    updated_at: '2024-06-10T10:00:00Z',
  },
  {
    id: 'q8',
    bank_id: 'qb3',
    type: 'single_choice',
    title: 'React useEffect cleanup',
    body: 'When does the cleanup function in useEffect run?',
    options: [
      { id: 'o21', text: 'Only when the component mounts', is_correct: false, order: 0 },
      { id: 'o22', text: 'Before the component unmounts and before every re-render with changed dependencies', is_correct: true, order: 1 },
      { id: 'o23', text: 'Only when the component unmounts', is_correct: false, order: 2 },
      { id: 'o24', text: 'After every render', is_correct: false, order: 3 },
    ],
    explanation: 'The cleanup function runs before the component unmounts and before re-running the effect due to changed dependencies.',
    points: 15,
    difficulty: 'medium',
    tags: ['hooks', 'useEffect', 'lifecycle'],
    category: 'React Hooks',
    created_at: '2024-06-15T10:00:00Z',
    updated_at: '2024-06-15T10:00:00Z',
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'a1',
    title: 'JavaScript Mastery Test',
    description: 'Comprehensive assessment covering core JavaScript concepts, async programming, and modern ES6+ features.',
    instructions: 'Read each question carefully. You have 60 minutes to complete all questions. No external resources allowed.',
    status: 'published',
    sections: [
      {
        id: 's1',
        title: 'Core Concepts',
        description: 'Fundamental JavaScript concepts',
        questions: mockQuestions.filter(q => q.bank_id === 'qb1').slice(0, 4),
        order: 0,
      },
      {
        id: 's2',
        title: 'Advanced Topics',
        description: 'Event loop, closures, and prototypes',
        questions: mockQuestions.filter(q => q.bank_id === 'qb1').slice(4),
        order: 1,
      },
    ],
    settings: {
      time_limit_minutes: 60,
      max_attempts: 3,
      shuffle_questions: true,
      shuffle_options: true,
      show_results: true,
      show_correct_answers: true,
      passing_score: 70,
      negative_marking: false,
      negative_marks_percentage: 0,
      require_fullscreen: false,
      allow_backtracking: true,
      auto_submit: true,
      show_leaderboard: true,
      certificate_enabled: true,
    },
    total_points: 85,
    total_questions: 6,
    attempts_count: 234,
    avg_score: 72,
    tags: ['javascript', 'programming'],
    created_by: 'u1',
    created_at: '2024-06-15T10:00:00Z',
    updated_at: '2024-07-20T14:30:00Z',
    published_at: '2024-06-20T09:00:00Z',
  },
  {
    id: 'a2',
    title: 'Data Structures & Algorithms',
    description: 'Test your understanding of fundamental data structures and algorithm design patterns.',
    status: 'published',
    sections: [{
      id: 's3',
      title: 'All Questions',
      questions: [mockQuestions[6]],
      order: 0,
    }],
    settings: {
      time_limit_minutes: 90,
      max_attempts: 2,
      shuffle_questions: false,
      shuffle_options: true,
      show_results: true,
      show_correct_answers: false,
      passing_score: 60,
      negative_marking: true,
      negative_marks_percentage: 25,
      require_fullscreen: true,
      allow_backtracking: true,
      auto_submit: true,
      show_leaderboard: true,
      certificate_enabled: true,
    },
    total_points: 150,
    total_questions: 15,
    attempts_count: 156,
    avg_score: 65,
    tags: ['dsa', 'algorithms'],
    created_by: 'u1',
    created_at: '2024-05-25T08:00:00Z',
    updated_at: '2024-07-22T11:00:00Z',
    published_at: '2024-06-01T09:00:00Z',
  },
  {
    id: 'a3',
    title: 'React Certification Exam',
    description: 'Professional React certification covering hooks, performance, patterns, and testing.',
    status: 'draft',
    sections: [{
      id: 's4',
      title: 'React Fundamentals',
      questions: [mockQuestions[7]],
      order: 0,
    }],
    settings: {
      time_limit_minutes: 120,
      max_attempts: 1,
      shuffle_questions: true,
      shuffle_options: true,
      show_results: true,
      show_correct_answers: true,
      passing_score: 80,
      negative_marking: false,
      negative_marks_percentage: 0,
      require_fullscreen: true,
      allow_backtracking: false,
      auto_submit: true,
      show_leaderboard: false,
      certificate_enabled: true,
    },
    total_points: 200,
    total_questions: 25,
    attempts_count: 0,
    avg_score: 0,
    tags: ['react', 'frontend', 'certification'],
    created_by: 'u1',
    created_at: '2024-07-10T10:00:00Z',
    updated_at: '2024-07-25T16:00:00Z',
  },
  {
    id: 'a4',
    title: 'Python Data Science Fundamentals',
    description: 'Assessment covering NumPy, Pandas, data visualization, and basic ML concepts.',
    status: 'published',
    sections: [],
    settings: {
      time_limit_minutes: 45,
      max_attempts: 5,
      shuffle_questions: true,
      shuffle_options: false,
      show_results: true,
      show_correct_answers: true,
      passing_score: 50,
      negative_marking: false,
      negative_marks_percentage: 0,
      require_fullscreen: false,
      allow_backtracking: true,
      auto_submit: false,
      show_leaderboard: true,
      certificate_enabled: false,
    },
    total_points: 100,
    total_questions: 20,
    attempts_count: 412,
    avg_score: 78,
    tags: ['python', 'data-science'],
    created_by: 'u1',
    created_at: '2024-04-20T09:00:00Z',
    updated_at: '2024-07-18T13:00:00Z',
    published_at: '2024-05-01T09:00:00Z',
  },
  {
    id: 'a5',
    title: 'System Design Interview Prep',
    description: 'Practice system design concepts including scalability, databases, and distributed systems.',
    status: 'published',
    sections: [],
    settings: {
      time_limit_minutes: 180,
      max_attempts: 1,
      shuffle_questions: false,
      shuffle_options: false,
      show_results: true,
      show_correct_answers: true,
      passing_score: 70,
      negative_marking: false,
      negative_marks_percentage: 0,
      require_fullscreen: false,
      allow_backtracking: true,
      auto_submit: true,
      show_leaderboard: false,
      certificate_enabled: true,
    },
    total_points: 300,
    total_questions: 10,
    attempts_count: 89,
    avg_score: 61,
    tags: ['system-design', 'architecture'],
    created_by: 'u1',
    created_at: '2024-07-05T10:00:00Z',
    updated_at: '2024-07-25T15:00:00Z',
    published_at: '2024-07-10T09:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  total_assessments: 24,
  total_questions: 487,
  total_attempts: 1893,
  total_students: 342,
  avg_score: 73.5,
  completion_rate: 87.2,
  assessments_this_month: 5,
  attempts_this_month: 312,
};

export const mockActivities: Activity[] = [
  {
    id: 'act1',
    type: 'attempt_completed',
    title: 'Assessment completed',
    description: 'Alex Kim scored 92% on JavaScript Mastery Test',
    user_name: 'Alex Kim',
    timestamp: '2024-07-25T14:30:00Z',
  },
  {
    id: 'act2',
    type: 'quiz_published',
    title: 'Assessment published',
    description: 'System Design Interview Prep is now live',
    user_name: 'Sarah Chen',
    timestamp: '2024-07-25T10:00:00Z',
  },
  {
    id: 'act3',
    type: 'certificate_issued',
    title: 'Certificate issued',
    description: 'Emily Davis received React Certification',
    user_name: 'Emily Davis',
    timestamp: '2024-07-24T16:45:00Z',
  },
  {
    id: 'act4',
    type: 'question_added',
    title: 'Questions added',
    description: '12 new questions added to Python Data Science bank',
    user_name: 'Sarah Chen',
    timestamp: '2024-07-24T11:20:00Z',
  },
  {
    id: 'act5',
    type: 'user_joined',
    title: 'New student',
    description: 'Marcus Lee joined the platform',
    user_name: 'Marcus Lee',
    timestamp: '2024-07-24T09:00:00Z',
  },
  {
    id: 'act6',
    type: 'attempt_completed',
    title: 'Assessment completed',
    description: 'Jordan Smith scored 85% on Data Structures & Algorithms',
    user_name: 'Jordan Smith',
    timestamp: '2024-07-23T15:30:00Z',
  },
  {
    id: 'act7',
    type: 'quiz_created',
    title: 'Assessment created',
    description: 'React Certification Exam draft created',
    user_name: 'Sarah Chen',
    timestamp: '2024-07-23T10:15:00Z',
  },
];

export const mockAttempts: Attempt[] = [
  {
    id: 'att1',
    assessment_id: 'a1',
    student_id: 's1',
    student_name: 'Alex Kim',
    status: 'graded',
    score: 78,
    total_points: 85,
    percentage: 92,
    responses: [
      { question_id: 'q1', answer: 'o1', time_spent_seconds: 45, is_correct: true, points_earned: 10 },
      { question_id: 'q2', answer: ['o5', 'o6', 'o8', 'o9'], time_spent_seconds: 60, is_correct: true, points_earned: 15 },
      { question_id: 'q3', answer: 'o12', time_spent_seconds: 15, is_correct: true, points_earned: 5 },
      { question_id: 'q4', answer: 'map', time_spent_seconds: 30, is_correct: true, points_earned: 10 },
      { question_id: 'q5', answer: 'o14', time_spent_seconds: 90, is_correct: true, points_earned: 20 },
      { question_id: 'q6', answer: 'Prototypal inheritance is...', time_spent_seconds: 300, is_correct: true, points_earned: 18 },
    ],
    started_at: '2024-07-25T14:00:00Z',
    submitted_at: '2024-07-25T14:30:00Z',
    time_spent_seconds: 1800,
  },
  {
    id: 'att2',
    assessment_id: 'a1',
    student_id: 's2',
    student_name: 'Emily Davis',
    status: 'graded',
    score: 60,
    total_points: 85,
    percentage: 71,
    responses: [
      { question_id: 'q1', answer: 'o1', time_spent_seconds: 60, is_correct: true, points_earned: 10 },
      { question_id: 'q2', answer: ['o5', 'o6', 'o7', 'o8'], time_spent_seconds: 45, is_correct: false, points_earned: 0 },
      { question_id: 'q3', answer: 'o12', time_spent_seconds: 10, is_correct: true, points_earned: 5 },
      { question_id: 'q4', answer: 'filter', time_spent_seconds: 40, is_correct: false, points_earned: 0 },
      { question_id: 'q5', answer: 'o14', time_spent_seconds: 120, is_correct: true, points_earned: 20 },
      { question_id: 'q6', answer: 'Prototypal inheritance allows...', time_spent_seconds: 240, is_correct: true, points_earned: 25 },
    ],
    started_at: '2024-07-24T10:00:00Z',
    submitted_at: '2024-07-24T10:45:00Z',
    time_spent_seconds: 2700,
  },
];

export const mockAnalytics: AnalyticsData = {
  performance_trend: [
    { date: 'Jan', avg_score: 65, attempts: 120 },
    { date: 'Feb', avg_score: 68, attempts: 145 },
    { date: 'Mar', avg_score: 71, attempts: 190 },
    { date: 'Apr', avg_score: 69, attempts: 210 },
    { date: 'May', avg_score: 74, attempts: 256 },
    { date: 'Jun', avg_score: 76, attempts: 280 },
    { date: 'Jul', avg_score: 73, attempts: 312 },
  ],
  difficulty_distribution: [
    { difficulty: 'Easy', count: 156 },
    { difficulty: 'Medium', count: 210 },
    { difficulty: 'Hard', count: 121 },
  ],
  question_type_distribution: [
    { type: 'Single Choice', count: 180 },
    { type: 'Multiple Choice', count: 120 },
    { type: 'True/False', count: 85 },
    { type: 'Fill Blank', count: 52 },
    { type: 'Essay', count: 50 },
  ],
  top_assessments: [
    { name: 'Python Data Science', attempts: 412, avg_score: 78 },
    { name: 'JS Mastery', attempts: 234, avg_score: 72 },
    { name: 'DSA', attempts: 156, avg_score: 65 },
    { name: 'System Design', attempts: 89, avg_score: 61 },
  ],
  topic_mastery: [
    { topic: 'Variables & Types', score: 88 },
    { topic: 'Functions', score: 82 },
    { topic: 'Arrays & Objects', score: 76 },
    { topic: 'Async/Await', score: 68 },
    { topic: 'Closures', score: 64 },
    { topic: 'Prototypes', score: 58 },
  ],
  score_distribution: [
    { range: '0-20%', count: 12 },
    { range: '21-40%', count: 34 },
    { range: '41-60%', count: 89 },
    { range: '61-80%', count: 156 },
    { range: '81-100%', count: 121 },
  ],
  time_analysis: [
    { question: 'Q1', avg_time: 45 },
    { question: 'Q2', avg_time: 60 },
    { question: 'Q3', avg_time: 15 },
    { question: 'Q4', avg_time: 35 },
    { question: 'Q5', avg_time: 95 },
    { question: 'Q6', avg_time: 270 },
  ],
};

export const mockCertificates: Certificate[] = [
  {
    id: 'cert1',
    attempt_id: 'att1',
    assessment_title: 'JavaScript Mastery Test',
    student_name: 'Alex Kim',
    score: 78,
    percentage: 92,
    issued_at: '2024-07-25T14:35:00Z',
    verification_code: 'QF-2024-JS-A1K2',
    template: 'modern',
  },
  {
    id: 'cert2',
    attempt_id: 'att2',
    assessment_title: 'JavaScript Mastery Test',
    student_name: 'Emily Davis',
    score: 60,
    percentage: 71,
    issued_at: '2024-07-24T10:50:00Z',
    verification_code: 'QF-2024-JS-E3D4',
    template: 'modern',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    title: 'New Submission',
    message: 'Alex Kim completed JavaScript Mastery Test with 92%',
    type: 'success',
    read: false,
    timestamp: '2024-07-25T14:30:00Z',
  },
  {
    id: 'n2',
    title: 'Assessment Published',
    message: 'System Design Interview Prep is now available to students',
    type: 'info',
    read: false,
    timestamp: '2024-07-25T10:00:00Z',
  },
  {
    id: 'n3',
    title: 'Low Score Alert',
    message: '3 students scored below 40% on DSA assessment',
    type: 'warning',
    read: true,
    timestamp: '2024-07-24T09:00:00Z',
  },
];
